---
# BEGIN
server:
  port: 7070

logging:
  level:
    root: WARN

spring:
  output:
    ansi:
      enabled: always
# END

users:
  admins:
    - gjoinsey1@blogger.com
    - scrosi4@cam.ac.uk
    - scrosi4@cam.ac.uk

